import Link from "next/link";
import { q } from "@/lib/duckdb";
import { lintAll, tapTypes } from "@/lib/config";
import {
  Badge,
  Card,
  Note,
  PageHeader,
  Stat,
  StatRow,
  Table,
  Td,
  classTone,
} from "@/components/ui";
import { duration, pct, titleize } from "@/lib/format";

export const dynamic = "force-dynamic";

export default async function Overview() {
  const types = tapTypes();
  const errors = lintAll().filter((f) => f.severity === "error").length;

  const [head, precision, recent] = await Promise.all([
    q<{
      taps: number;
      answered: number;
      strategic: number;
      unresolved: number;
      landed: number;
      median: number;
    }>(`SELECT
          (SELECT COUNT(*) FROM taps)                                          AS taps,
          (SELECT COUNT(*) FROM taps WHERE status = 'answered')                AS answered,
          (SELECT COUNT(*) FROM taps WHERE tap_class = 'strategic')            AS strategic,
          (SELECT COUNT(*) FROM taps WHERE status IN ('timed_out','expired'))  AS unresolved,
          (SELECT COUNT(*) FROM write_backs WHERE status IN ('merged','applied')) AS landed,
          (SELECT ROUND(MEDIAN(minutes_to_respond),0) FROM tap_responses)      AS median`),
    q<{ tap_type_id: string; precision_pct: number | null; verdict: string }>(
      `SELECT tap_type_id, precision_pct, verdict FROM v_precision_by_type ORDER BY precision_pct`
    ),
    q<{ tap_id: string; tap_type_id: string; tap_class: string; recipient_name: string; answer: string | null; status: string; minutes_to_respond: number | null }>(
      `SELECT tap_id, tap_type_id, tap_class, recipient_name, answer, status, minutes_to_respond
       FROM v_tap_detail ORDER BY delivered_at DESC LIMIT 8`
    ),
  ]);
  const h = head[0];
  const belowBar = precision.filter((p) => p.verdict === "below bar");

  return (
    <>
      <PageHeader
        eyebrow={
          <>
            <Link href="/" className="hover:underline">
              Tap AI
            </Link>{" "}
            / design notes
          </>
        }
        title="What this MVP argues, and where it was wrong"
        lede="Internal page — not on the customer path. The scorecard below is real activity from the seeded warehouse; the three findings underneath each changed a design decision while building it."
      />

      <StatRow>
        <Stat
          label="Taps delivered"
          value={h.taps.toLocaleString()}
          sub={`${h.strategic} strategic · ${(h.taps - h.strategic).toLocaleString()} tactical`}
        />
        <Stat
          label="Answer rate"
          value={pct((h.answered / h.taps) * 100)}
          sub={`median ${duration(h.median)} to respond`}
          tone={h.answered / h.taps > 0.6 ? "good" : "warn"}
        />
        <Stat label="Artifacts landed" value={h.landed.toLocaleString()} sub="merged PRs and applied overrides" />
        <Stat
          label="Tap types below bar"
          value={belowBar.length}
          sub={belowBar.length ? belowBar.map((b) => titleize(b.tap_type_id)).join(", ") : "all above 60% precision"}
          tone={belowBar.length ? "bad" : "good"}
        />
      </StatRow>

      <div className="mt-6 grid gap-5 lg:grid-cols-[1.25fr_1fr]">
        <div className="space-y-5">
          <Card title="What this MVP proves, and what it does not" subtitle="Worth being precise about before anyone reads the charts.">
            <div className="space-y-3.5">
              <div>
                <p className="text-xs font-semibold text-teal-800">It does test loop mechanics</p>
                <p className="mt-1 text-xs leading-relaxed text-slate-700">
                  Whether a tap can be routed to the right person, answered in seconds, and turned
                  into an artifact that lands. Every tap here was generated by a tap type a human
                  authored, so relevance is assumed rather than demonstrated.
                </p>
              </div>
              <div>
                <p className="text-xs font-semibold text-rose-800">It does not test tap quality</p>
                <p className="mt-1 text-xs leading-relaxed text-slate-700">
                  Whether a machine can generate questions people find worth answering is a separate
                  and riskier bet. Bundling the two means a failure is unattributable: if taps are
                  mediocre nobody answers, and you learn nothing about the mechanics. Run that as a
                  paper experiment first — 30 candidate taps, 5 real stakeholders, one question each:
                  would you have wanted to be asked this?
                </p>
              </div>
              <div>
                <p className="text-xs font-semibold text-slate-800">Deliberately absent</p>
                <p className="mt-1 text-xs leading-relaxed text-slate-700">
                  LLM classification, live IdP, real Slack delivery, anomaly detection against a real
                  warehouse, and the audit trigger. All four are off in{" "}
                  <code className="text-[10px]">config/sources.yml</code> on purpose.
                </p>
              </div>
            </div>
          </Card>

          <Card title="Three findings from building it" subtitle="Each changed a design decision.">
            <ol className="space-y-3.5">
              {[
                [
                  "Write-back has to fork by tap class",
                  "The original spine said write-back is a PR into a git repo, universally. A record-level tactical answer is data, not a code change — a PR per tactical tap drowns the repo and buries the strategic taps that need review. Strategic goes to a PR; tactical accumulates in an override table.",
                  "/tap-types",
                ],
                [
                  "Most tap types exhaust their own question space",
                  "Dedupe keyed on a fixed taxonomy bounds how many distinct questions a type can ever ask. Seven of eight types here decay to near zero; only the one tied to ongoing code creation sustains. That is the product working as intended, and it breaks per-tap pricing.",
                  "/analytics",
                ],
                [
                  "Routing has a hidden ontology, and deflection is how you pay for it",
                  "An IdP knows org structure, not who owns the revenue definition. Domain ownership is the one ontology that cannot be avoided — so make it small, let it start wrong, and converge it from 'not me, ask Dana' clicks rather than authoring it up front.",
                  "/config",
                ],
              ].map(([title, body, href], i) => (
                <li key={String(title)} className="flex gap-3">
                  <span className="mt-0.5 flex h-5 w-5 shrink-0 items-center justify-center rounded-full bg-slate-900 text-[10px] font-semibold text-white">
                    {i + 1}
                  </span>
                  <div>
                    <Link href={String(href)} className="text-xs font-semibold text-slate-900 hover:text-teal-700">
                      {title} →
                    </Link>
                    <p className="mt-1 text-xs leading-relaxed text-slate-600">{body}</p>
                  </div>
                </li>
              ))}
            </ol>
          </Card>

          <Card title="Latest activity" subtitle="">
            <Table head={["Tap", "Type", "Recipient", "Outcome", "Latency"]} dense>
              {recent.map((r) => (
                <tr key={r.tap_id} className="hover:bg-slate-50/70">
                  <Td mono>
                    <Link href={`/inbox/${r.tap_id}`} className="text-teal-700 hover:underline">
                      {r.tap_id}
                    </Link>
                  </Td>
                  <Td>
                    <Badge tone={classTone(r.tap_class)}>{r.tap_class}</Badge>
                    <div className="mt-1 text-[10px] text-slate-500">{titleize(r.tap_type_id)}</div>
                  </Td>
                  <Td className="text-xs">{r.recipient_name}</Td>
                  <Td className="text-[11px]">{r.answer ?? titleize(r.status)}</Td>
                  <Td className="tabular-nums text-xs">{duration(r.minutes_to_respond)}</Td>
                </tr>
              ))}
            </Table>
          </Card>
        </div>

        <div className="space-y-5">
          <Card title="Where to look" subtitle="">
            <ul className="space-y-2.5">
              {[
                ["/", "Homepage", "The customer-facing surface, with the five-scenario tap simulator."],
                ["/inbox", "Tap inbox", "The alert itself, in three surfaces, plus an end-to-end trace of any single tap."],
                ["/tap-types", "Tap types", "The primitive. Eight specs, a lint report, and the precision gate that decides what ships."],
                ["/analytics", "Analytics", "Funnel, per-type decay, routing quality, and who is carrying the context load."],
                ["/pricing", "Pricing", "Capability tiers keyed on connectors and whether company-level decisions are included, plus value shown as arithmetic."],
                ["/config", "Configuration", "Source connection, SSO, domain ownership, and notification caps."],
              ].map(([href, label, desc]) => (
                <li key={href}>
                  <Link href={href} className="text-xs font-semibold text-teal-700 hover:underline">
                    {label}
                  </Link>
                  <p className="mt-0.5 text-[11px] leading-relaxed text-slate-600">{desc}</p>
                </li>
              ))}
            </ul>
          </Card>

          <Card title="System state" subtitle="">
            <dl className="space-y-1.5 text-[11px]">
              {[
                ["Tap types", `${types.length} (${types.filter((t) => t.status === "active").length} active)`],
                ["Lint errors", String(errors)],
                ["Never answered", `${h.unresolved} taps timed out or expired`],
                ["Source adapter", "dbt — seeded, not yet live"],
                ["SSO", "simulated from org/employees.csv"],
                ["Delivery", "local webapp only"],
              ].map(([k, v]) => (
                <div key={String(k)} className="flex justify-between gap-3 border-b border-slate-50 pb-1">
                  <dt className="text-slate-500">{k}</dt>
                  <dd className="text-right font-medium text-slate-800">{v}</dd>
                </div>
              ))}
            </dl>
          </Card>

          <Note title="The riskiest assumption">
            Precision, because the payoff is asymmetric. A good tap saves an hour; a bad tap costs you
            the channel permanently. Notification products die of false positives, not of missed true
            positives. That argues for a human gate on outbound taps in v1 — an analytics engineer
            approving the queue — even though it does not scale. Prove the ceiling before automating
            toward it.
          </Note>
        </div>
      </div>
    </>
  );
}
